
PIECE_SIZE = 80
BORDER_SIZE = 2

PIECE_WIDTH = PIECE_SIZE * 1 + BORDER_SIZE * 2
PIECE_HEIGHT = PIECE_SIZE * 1 + BORDER_SIZE * 2

SCREEN_WIDTH = 1200
SCREEN_HEIGHT = 700 + (PIECE_HEIGHT * 2)

BACKGROUND = "#63d14f"
FOREGROUND = "#FFCF85"
FOREGROUND_ACCENT_1 = "#E4AB72"
FOREGROUND_ACCENT_2 = "#BB854E"
SELECTED_COLOR = "#C2FFFD"
MOVE_COLOR = "#caa7fc"
WHITE = "#FFFFFF"
BLACK = "#000000"


ROWS = 6
COLS = 8
