
PIECE_SIZE = 80
BORDER_SIZE = 2

PIECE_WIDTH = PIECE_SIZE * 1 + BORDER_SIZE * 2
PIECE_HEIGHT = PIECE_SIZE * 1 + BORDER_SIZE * 2
BOARD_WIDTH = PIECE_WIDTH * 8
BOARD_HEIGHT = PIECE_HEIGHT * 8

SCREEN_WIDTH = 1200
SCREEN_HEIGHT = 700 + (PIECE_HEIGHT * 2)

BACKGROUND = "#63d14f"
FOREGROUND = "#FFCF85"
FOREGROUND_ACCENT_1 = "#E4AB72"
FOREGROUND_ACCENT_2 = "#BB854E"
SELECTED_COLOR = "#C2FFFD"
MOVE_COLOR = "#caa7fc"
MOVE_COLOR_TRANSLUCENT = "#caa7fc80"

WHITE = "#FFFFFF"
BLACK = "#000000"
GRAY = "#b5b5b5"

PIECE_BLUE = "#039dfc"
PIECE_BLUE_SURFACE = "#0065a3"
PIECE_ORANGE = "#ffa01c"
PIECE_ORANGE_SURFACE = "#ed8a00"

ROWS = 6
COLS = 8

# small board
ROWS_SMALL = 5
COLS_SMALL = 6

BOARD_WIDTH_SMALL = PIECE_WIDTH * COLS_SMALL
BOARD_HEIGHT_SMALL = PIECE_HEIGHT * COLS_SMALL

current_menu = None